#
# This file was automatically generated by s2e-env at {{ creation_time }}
#
# This script is used to launch the test.
#

on_exit() {
    local CODE=$?

    if [ $CODE -ne 0 ]; then
        echo FAILURE > $S2E_LAST/status
        echo FAILURE
    else
        echo SUCCESS > $S2E_LAST/status
        echo SUCCESS
    fi
}

if [ ! -d "$S2EDIR" ]; then
    echo "S2EDIR does not exist or is not set. Please set it to the root of your S2E environment"
    exit 1
fi

trap "on_exit" EXIT

set -xe

ulimit -c unlimited

DIR_NAME="$(cd $(dirname $0) && pwd)"
S2E_LAST="$DIR_NAME/s2e-last"

get_bitness() {
    local TARGET_NAME="$(basename $1)"
    if echo $TARGET_NAME | grep -q 32; then
        echo 32
    elif echo $TARGET_NAME | grep -q 64; then
        echo 64
    else
        echo "Invalid bitness encoded in $TARGET_NAME"
        exit 1
    fi
}

get_platform() {
    local TARGET_NAME="$(basename $1)"
    if echo $TARGET_NAME | grep -q windows; then
        echo windows
    elif echo $TARGET_NAME | grep -q linux; then
        echo linux
    else
        echo "Invalid platform encoded in $TARGET_NAME"
        exit 1
    fi
}
