# Copyright (C) 2021 Vitaly Chipounov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

$boxes = ["debian/bullseye64", "debian/bookworm64", "generic/ubuntu2004", "generic/ubuntu2204"]

Vagrant.configure("2") do |config|
  $boxes.to_enum.with_index(1).each do |box,i|
    config.vm.define "s2e_machine_#{i}" do |node|
      node.vm.box = box
      node.vm.synced_folder ".", "/vagrant", type: "rsync"
      node.vm.provision :shell do |s|
        s.path = "provision-root.sh"
      end

      node.ssh.forward_agent = true
      node.ssh.forward_x11 = true

      node.vm.provider :libvirt do |v|
        v.cpus = 16
        v.memory = 16384
        v.storage :file, :size => '100G'
      end
    end
  end
end
