name: Build libs2e.so
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install packages
        run: |
            set -ex
            sudo dpkg --add-architecture i386 && sudo apt-get update
            sudo apt-get -y install ca-certificates build-essential curl wget texinfo flex bison  \
              python-is-python3 python3-dev python3-venv python3-distro mingw-w64 lsb-release \
              libdwarf-dev libelf-dev cmake \
              libboost-dev zlib1g-dev libjemalloc-dev nasm pkg-config  \
              libmemcached-dev libpq-dev binutils-dev \
              libboost-system-dev libboost-serialization-dev libboost-regex-dev \
              libbsd-dev libpixman-1-dev \
              libglib2.0-dev python3-docutils libpng-dev \
              gcc-multilib g++-multilib libgomp1 unzip software-properties-common \
              libprotobuf-dev protobuf-compiler protobuf-c-compiler \
              libgmock-dev libgtest-dev rapidjson-dev libsoci-dev libcapstone-dev

            sudo apt-get install -f
            sudo apt-get install -y libgcc-s1:i386 libstdc++6:i386
            sudo apt-get install -y libglib2.0-dev:i386 libelf-dev:i386

      - name: Build libs2e.so
        run: |
           set -x
           cd ..
           mkdir build && cd build
           make -f ../s2e/Makefile all
      - run: echo "🍏 This job's status is ${{ job.status }}."
